version: '3'

services:
  api:
    build:
      context: .
    image: simple/api
    container_name: simple-api
    volumes:
      - .:/usr/src/app/
    ports:
      - 3993:3993
    env_file:
      - .env
    command: npm start
    depends_on:
      - postgres
    networks:
      - backend

  postgres:
    image: postgres:12.2-alpine
    container_name: simple-postgres
    ports:
      - 7887:5432
    command: postgres -c 'max_connections=1000' -c idle_in_transaction_session_timeout='30s'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    driver: bridge
